name: Release

on:
  workflow_run:
    workflows: ["Audit"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: build
      run: make build/api
      
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.PROD_HOST_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.KEY }}
        script: make production/deploy
